id = "polycarbonate-dark-theme"
name = "Polycarbonate Dark Theme"
version = "0.0.1"
schema_version = 1
authors = ["Sha1rholder <sha1rholder@outlook.com>"]
description = "Turn Zed into a clean slab of dark glass."
repository = "https://github.com/Sha1rholder/polycarbonate-dark-theme"
